version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 10
    reviewers:
      - "VibeCodingWithPhil"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "deps"
      include: "scope"
    
  # Enable security updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"
    reviewers:
      - "VibeCodingWithPhil"
    labels:
      - "security"
      - "dependencies"
    allow:
      - dependency-type: "all"
    
  # Enable updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "VibeCodingWithPhil"
    labels:
      - "github-actions"
      - "dependencies"
    commit-message:
      prefix: "ci"